#### 0关闭 1开启 ####


### fs ###
fs.file-max=4194304
fs.inotify.max_user_instances=262144
fs.inotify.max_user_watches=262144
fs.nr_open=1048576


### kernel ###
kernel.core_uses_pid=1
kernel.sysrq=0


### net ###
## core ##
net.core.default_qdisc=cake
net.core.netdev_max_backlog=65536
#TCP协议栈的最大连接数
net.core.somaxconn=65536
#TCP套接字最多可以使用的选项内存大小 (byte)
#256M
net.core.optmem_max=268435456
#TCP套接字的默认接收缓冲区  (byte)
#16M
net.core.rmem_default=16777216
#128M
net.core.rmem_max=134217728
#TCP套接字的默认发送缓冲区 (byte)
#16M
net.core.wmem_default=16777216
#128M
net.core.wmem_max=134217728

## ipv4 ##
net.ipv4.conf.all.rp_filter=1
net.ipv4.conf.default.rp_filter=1
net.ipv4.ip_default_ttl=64
net.ipv4.ip_forward=1
net.ipv4.ip_local_port_range=32767 61000
net.ipv4.route.flush=1
net.ipv4.tcp_adv_win_scale=-2
net.ipv4.tcp_congestion_control=bbr
net.ipv4.tcp_ecn=1
net.ipv4.tcp_ecn_fallback=1
net.ipv4.tcp_fastopen=3
net.ipv4.tcp_fin_timeout=15
net.ipv4.tcp_keepalive_time=300
net.ipv4.tcp_keepalive_intvl=5
net.ipv4.tcp_keepalive_probes=15
net.ipv4.tcp_low_latency=1
#系统中最多可以保留多少个孤立（orphan）连接
net.ipv4.tcp_max_orphans=65536
#系统中最多可以保留多少个无效的时间等待（TIME_WAIT）状态的连接
net.ipv4.tcp_max_tw_buckets=360000
net.ipv4.tcp_mtu_probing=1
#缓冲区中未发送数据的字节数低于指定值时，TCP将向应用程序发送通知 (byte)
#128k
net.ipv4.tcp_notsent_lowat=131072
net.ipv4.tcp_rfc1337=1
net.ipv4.tcp_sack=1
net.ipv4.tcp_syn_retries=2
net.ipv4.tcp_synack_retries=2
net.ipv4.tcp_syncookies=1
net.ipv4.tcp_timestamps=1
net.ipv4.tcp_tw_reuse=1
net.ipv4.tcp_window_scaling=1
#单个TCP连接每次发送数据量的最大限制 (byte)
#16M
net.ipv4.tcp_limit_output_bytes=16777216
#TCP协议的内存池(4K) 32M 64M 128M
net.ipv4.tcp_mem=8192 16384 32768
#缓冲区 (minimum default maximum) (byte)
#       (4K      16M     64M)
net.ipv4.tcp_rmem=4096 16777216 67108864
net.ipv4.tcp_wmem=4096 16777216 67108864
#UDP协议的内存池(4K) 32M 64M 128M
net.ipv4.udp_mem=8192 16384 32768
#UDP最小缓冲区 (byte)
#16K
net.ipv4.udp_rmem_min=16384
net.ipv4.udp_wmem_min=16384

## ipv6 ##
net.ipv6.route.flush=1


### vw ###
## swap ##
vm.dirty_background_ratio=2
vm.dirty_ratio=60
vm.swappiness=5

